
name: kodi-omega
version: 21.2.0
summary: kodi-omega
description: |
  Unofficial Kodi-Omega Snap
  Kodi is an open-source media center software that 
  lets you play movies, music, TV shows, and more.
  This is an unofficial build that includes all available plugins
  from the official repository.
  PulseAudio and X11 are required for smooth operation.
  It doesn't work with wayland.
  Start from terminal with " kodi-omega ".
  For iptv you need a m3u File. 
  Enjoy your media with Kodi!
  Known Issues: Vaapi ist not working

confinement: strict
grade: stable
base: core24
source-code: https://github.com/Tibsun75/kodi-omega-snap
platforms:
  amd64:


parts:
  kodi-omega:
    plugin: cmake
    source: https://github.com/xbmc/xbmc.git
    source-branch: Omega
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -DCORE_PLATFORM_NAME=x11
      - -DAPP_RENDER_SYSTEM=gl
      - -DENABLE_INTERNAL_FFMPEG=ON
      - -DENABLE_INTERNAL_FMT=ON
      - -DENABLE_INTERNAL_FLATBUFFERS=ON
      - -DENABLE_VAAPI=ON
      - -DENABLE_VDPAU=OFF 
      - -DCMAKE_BUILD_TYPE=Release

    build-packages:
      - debhelper
      - autoconf
      - automake
      - autopoint
      - gettext
      - autotools-dev
      - cmake
      - curl
      - default-jre
      - doxygen
      - gawk
      - gcc
      - gdc
      - gperf
      - libasound2-dev
      - libass-dev
      - libavahi-client-dev
      - libavahi-common-dev
      - libbluetooth-dev
      - libbluray-dev
      - libbz2-dev
      - libcdio-dev
      - libp8-platform-dev
      - libcrossguid-dev
      - libcurl4-openssl-dev
      - libcwiid-dev
      - libdbus-1-dev
      - libdrm-dev
      - libegl1-mesa-dev
      - libenca-dev
      - libexiv2-dev
      - libflac-dev
      - libfmt-dev
      - libfontconfig-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libfstrcmp-dev
      - libgcrypt-dev
      - libgif-dev
      - libgles2-mesa-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libgnutls28-dev
      - libgpg-error-dev
      - libgtest-dev
      - libiso9660-dev
      - libjpeg-dev
      - liblcms2-dev
      - libltdl-dev
      - liblzo2-dev
      - libmicrohttpd-dev
      - libmysqlclient-dev
      - libnfs-dev
      - libogg-dev
      - libpcre2-dev
      - libplist-dev
      - libpng-dev
      - libpulse-dev
      - libshairplay-dev
      - libsmbclient-dev
      - libspdlog-dev
      - libsqlite3-dev
      - libssl-dev
      - libtag1-dev
      - libtiff5-dev
      - libtinyxml-dev
      - libtinyxml2-dev
      - libtool
      - libudev-dev
      - libunistring-dev
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libxmu-dev
      - libxrandr-dev
      - libxslt1-dev
      - libxt-dev
      - lsb-release
      - meson
      - nasm
      - ninja-build
      - nlohmann-json3-dev
      - python3-dev
      - python3-pil
      - python3-pip
      - swig
      - unzip
      - uuid-dev
      - zip
      - zlib1g-dev
      - libpcre3-dev
      - rapidjson-dev
      - libavcodec-dev

    stage-packages:
      - libass9
      - libcdio19t64
      - libgif7
      - libjpeg-turbo8
      - libcurl4t64
      - libldap2
      - libnghttp2-14
      - libpsl5t64
      - libpython3.12t64
      - libegl1
      - libgl1
      - libglx0
      - libxrandr2
      - libasound2t64
      - libavahi-client3
      - libavahi-common3
      - libbluetooth3
      - libbluray2
      - libcec6
      - libsmbclient0
      - libexiv2-27
      - libfstrcmp0
      - liblcms2-2
      - liblirc-client0t64
      - libmicrohttpd12t64
      - libmysqlclient21
      - libnfs14
      - libplist-2.0-4
      - libpulse0
      - apulse
      - libtag1v5-vanilla
      - libtinyxml2.6.2v5
      - libva-drm2
      - libva-x11-2
      - libva-glx2
      - libva-wayland2
      - libvdpau1
      - libxslt1.1
      - libshairplay0
      - libtinyxml2-10
      - libgl1-mesa-dri
      - libpulse0
      - libvdpau-va-gl1
      - libva2
      - libva-drm2
      - libva-dev
      - libdrm2
      - i965-va-driver
      - i965-va-driver-shaders
      - intel-media-va-driver
      - mesa-va-drivers
      - libpcre3
      - libglu1-mesa
      - libigdgmm12
      - libfmt9
      - libspdlog-dev
            
    override-build: |
      craftctl default
      cd $CRAFT_PART_SRC
          
      # Adjust Kodi path in binary
      sed -i 's|/usr/local|$SNAP/usr/local|g' $SNAPCRAFT_PART_INSTALL/usr/local/bin/kodi
      
      # build all addos 
      make -j$(getconf _NPROCESSORS_ONLN) -C tools/depends/target/binary-addons PREFIX=$SNAPCRAFT_PART_INSTALL/usr/local
      

apps:
  kodi-omega:
      
    command: usr/local/lib/kodi/kodi-x11
    environment:
      # do not split this line
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/vdpau:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu/samba:$SNAP/lib/x86_64-linux-gnu:$LIBGL_DRIVERS_PATH:$SNAP/usr/local/lib/kodi:$LD_LIBRARY_PATH
      KODI_HOME: $SNAP/usr/local/share/kodi
      XBMCBIN: $SNAP/usr/local/lib/kodi
      LIBVA_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri
      PULSE_SERVER: unix:/run/user/1000/pulse/native
      
    plugs:
      - audio-playback
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - network-bind
      - network-status
      - media-hub
      - opengl
      - optical-drive
      - screen-inhibit-control
      - unity7
      - wayland
      - x11
      - pulseaudio
      - hardware-observe
      - avahi-observe
      - gsettings
      - joystick
      - upower-observe
      - removable-media

